# ADVANCED NUMPY

In [4]:
import numpy as np

In [5]:
A=[1,2,3,4,56]

In [6]:
c=np.array(A)
c

array([ 1,  2,  3,  4, 56])

In [7]:
type(c)

numpy.ndarray

In [8]:
b=np.array((1,2,3,4,5,6))

In [9]:
b

array([1, 2, 3, 4, 5, 6])

In [10]:
len(b)

6

In [11]:
b[-1:-4]

array([], dtype=int32)

In [12]:
b[-4:-1:-1]

array([], dtype=int32)

# COMPARISON BETWEEN LIST AND ARRAY

3 BENEFITS OF ARRAY

1) TAKES LESS MEMORY

2) FAST

3) CONVININENT

In [14]:
import time
import sys

In [15]:
l=range(200000)
print(sys.getsizeof(2)*len(l))

5600000


In [16]:
sys.getsizeof(2)

28

In [17]:
a=np.arange(200000)
print(a.itemsize*len(a))

800000


In [18]:
a

array([     0,      1,      2, ..., 199997, 199998, 199999])

2) FAST

In [27]:
a=[1,2,3,4,5]
b=[1,2,3,4,5]

In [20]:
[i+j for i,j in zip(a,b)]

[1, 3, 5, 7, 9, 11]

In [21]:
import numpy as np
import time

In [22]:
a1=range(10000000)
b1=range(10000000)

start=time.time()
c1=[(x+y) for x,y in zip(a1,b1)]
print( "time taken :",(time.time()-start))


time taken : 0.9025120735168457


In [23]:
a2=np.arange(10000000)
b2=np.arange(10000000)

start=time.time()
c2= a2+b2
print(" time taken by array :", (time.time()-start))

 time taken by array : 0.01200103759765625


In [25]:
c1

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

3) CONVININENT

In [180]:
n1=np.arange(100)
n2=np.arange(100)


In [182]:
n2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [186]:
n1/n2

C:\Users\eshan\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [19]:
n2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [20]:
a=[1,2,3,4,5,6]
b=[1,2,3,4,5,6]

d=[]
for i,j in zip(a,b):
    c=i+j
    d.append(c)
    

In [21]:
d

[2, 4, 6, 8, 10, 12]

In [ ]:
n4=n2-n1
n4

In [ ]:
n5=n2*n1
n5

In [ ]:
np.array(5.0)

In [ ]:
n6=n2/n1
n6

# BASIC OPERATIONS

In [42]:
import numpy as np


In [43]:
b=1,2,3

In [44]:
b

(1, 2, 3)

In [45]:
c=np.array(b)

In [46]:
c

array([1, 2, 3])

In [190]:
a=np.array([4,5,6],ndmin=10)

In [191]:
a

array([[[[[[[[[[4, 5, 6]]]]]]]]]])

In [188]:
type(a)

numpy.ndarray

In [192]:
a.ndim

10

In [69]:
b=np.array([1, 2, 3],ndmin=3)

In [70]:
b

array([[[1, 2, 3]]])

In [71]:
b.ndim

3

# UPCASTING

In [39]:
w=np.array([2,3,5],dtype="U1")

In [40]:
w

array(['2', '3', '5'], dtype='<U1')

In [203]:
c=np.array([ 2,9,100,234,453,9],dtype="float16")

In [204]:
c

array([  2.,   9., 100., 234., 453.,   9.], dtype=float16)

In [45]:
w=np.dtype("<U1")

In [100]:
d=np.dtype('U1')

In [46]:
w.name

'str32'

In [205]:
a=np.array([[1,2.2,3],[4,5,6]],dtype="U2")
a

array([['1', '2.', '3'],
       ['4', '5', '6']], dtype='<U2')

In [206]:
a.ndim

2

In [207]:
a.shape

(2, 3)

In [208]:
a.size

6

In [53]:
w=np.array([1,2,3,4],dtype="int64")

In [54]:
w.itemsize

8

In [132]:
a.size

6

In [133]:
a.dtype

dtype('<U2')

In [141]:
a=np.array([[1,2.2,3],[4,5,6]],dtype="<f4")

In [142]:
a

array([[1. , 2.2, 3. ],
       [4. , 5. , 6. ]])

In [143]:
a.itemsize

8

In [144]:
a.size

6

In [132]:
a.dtype

dtype('float64')

In [88]:
a

array([[1., 2., 3., 6.],
       [4., 5., 6., 9.]], dtype=float16)

In [46]:
a=np.array([[1,2,3],[4,5,6]],dtype="<U64")

In [47]:
a.itemsize

256

# SHALLOW AND DEEP COPY

In [55]:
l=[1,2,3,4,5]

In [56]:
l


[1, 2, 3, 4, 5]

In [57]:
l1=l

In [58]:
l1

[1, 2, 3, 4, 5]

In [59]:
l1[1]=100

In [60]:
l1

[1, 100, 3, 4, 5]

In [61]:
l

[1, 100, 3, 4, 5]

In [62]:
print(id(l1)),print(id(l))

2367320076808
2367320076808


(None, None)

In [63]:
l=[1,2,3,4,5]

In [64]:
l

[1, 2, 3, 4, 5]

In [65]:
l2=l.copy()

In [66]:
l2[1]=100

In [67]:
l2

[1, 100, 3, 4, 5]

In [68]:
l

[1, 2, 3, 4, 5]

In [69]:
print(id(l),id(l2))

2367307574664 2367306056136


In [159]:
l2[3]=100
l2

[1, 2, 3, 100, 5]

In [160]:
l

[1, 2, 3, 4, 5]

In [74]:
l=[[1,2,3],[4,56]]

In [75]:
l

[[1, 2, 3], [4, 56]]

In [76]:
l2=l.copy()

In [77]:
l2

[[1, 2, 3], [4, 56]]

In [78]:
l2[0][2]=100

In [79]:
l2

[[1, 2, 100], [4, 56]]

In [80]:
l

[[1, 2, 100], [4, 56]]

In [176]:
print(id(l)),print(id(l2))

1548863511112
1548801854344


(None, None)

In [81]:
import copy

In [82]:
l=[[1,2,3],[4,5,6]]

In [83]:
l2=copy.deepcopy(l)

In [84]:
l2

[[1, 2, 3], [4, 5, 6]]

In [85]:
l2[0][2]=100

In [86]:
l2

[[1, 2, 100], [4, 5, 6]]

In [87]:
l

[[1, 2, 3], [4, 5, 6]]

In [88]:
print(id(l2))

2367311498312


In [89]:
print(id(l))

2367320056008


# arange and linspace

In [248]:
list(range(0,11,.5))

TypeError: 'float' object cannot be interpreted as an integer

In [252]:
np.arange(-20,-2,-1)

array([], dtype=int32)

In [206]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [208]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [201]:
a[::-1]

array([9.8, 8.4, 7. , 5.6, 4.2, 2.8, 1.4, 0. ])

In [253]:
for i in np.arange(10,20):
    if i%2==0:
        print(i)

10
12
14
16
18


In [210]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [209]:
np.arange(50,-1,-5)

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [255]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [222]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [256]:
np.linspace(1,10,10,endpoint=False,retstep=True)

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), 0.9)

In [152]:
np.linspace(2.0, 3.0, num=5, endpoint=True)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [229]:
np.linspace(1,5,10, retstep=True)

(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
        3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]),
 0.4444444444444444)

In [155]:
np.linspace(2,3,5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [156]:
np.linspace(2,3,5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

# RESHAPE

In [3]:
import numpy as np

In [267]:
np.arange(32).reshape(8,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [285]:
x = np.arange(1,21).reshape(2,5,2)

In [286]:
x

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

# MATRIX CREATION

In [269]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [270]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [271]:
5*np.ones((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [272]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [273]:
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# DIAGONAL

In [274]:
x = np.arange(25).reshape(5,5)

In [275]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [277]:
np.diag(x)

array([ 0,  6, 12, 18, 24])

In [278]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0],
       [ 0,  0, 12,  0,  0],
       [ 0,  0,  0, 18,  0],
       [ 0,  0,  0,  0, 24]])

In [306]:
np.diag(np.diag(np.arange(16).reshape(4,4)))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [301]:
np.diagflat([[1,2,10], [3,4,10]])

array([[ 1,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0],
       [ 0,  0, 10,  0,  0,  0],
       [ 0,  0,  0,  3,  0,  0],
       [ 0,  0,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  0, 10]])

An array with ones at and below the given diagonal and zeros elsewhere

# Random number generation

Uniform distribution with random numbers ranging from 0 to 1

In [307]:
import numpy as np

In [308]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [283]:
np.random.randt(1,30,(2,5))

array([[27, 22,  8, 15,  6],
       [16, 10, 16,  4, 26]])

In [312]:
np.random.randint(60,100,(5,5))

array([[80, 64, 66, 68, 75],
       [77, 86, 80, 63, 81],
       [84, 98, 97, 82, 60],
       [66, 85, 66, 89, 81],
       [73, 74, 72, 95, 79]])

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal

In [285]:
np.random.randn(5,5)

array([[-9.56866989e-01,  2.16504012e-01, -2.84524935e-01,
         4.11648438e-02,  2.72946664e-01],
       [-1.13711251e+00,  2.08988361e-01,  9.75016791e-01,
        -8.94588363e-01, -1.72395939e+00],
       [ 1.33574397e-03, -3.42305711e-01, -6.03076397e-01,
        -5.24848844e-01,  9.27756913e-01],
       [ 9.00185902e-01,  1.86449953e+00,  1.03122188e+00,
         6.95419866e-01, -4.10167686e-01],
       [ 9.22353025e-01, -6.93703021e-01, -8.38196913e-01,
         1.09426089e+00,  3.61368853e-01]])

In [319]:
np.random.randint(100,1000,(5,4))

array([[334, 727, 499, 226],
       [754, 372, 229, 685],
       [513, 739, 265, 821],
       [294, 991, 151, 674],
       [761, 956, 398, 492]])

In [210]:
np.random.randint(1,100,(5,5))

array([[88, 16, 68, 71,  8],
       [58, 76, 28, 51,  1],
       [88, 36,  9, 26, 47],
       [36, 37, 24, 55, 17],
       [84, 39, 34, 20, 45]])

In [292]:
from numpy.random import randint as ri
a = ri(1,100,20).reshape(4,5)



In [293]:
a

array([[14, 30, 32,  5, 91],
       [49, 54,  1, 18,  4],
       [ 3, 68, 11, 55, 67],
       [93, 24,  3, 84,  6]])

In [4]:
c = a.reshape(6,5)

In [5]:
c

array([[41, 18, 64, 34, 27],
       [94, 94, 34, 12, 28],
       [61, 80, 47, 33, 16],
       [21, 47, 24,  7, 81],
       [93, 28, 67, 93, 99],
       [19, 41, 76, 47,  1]])

In [9]:
import numpy as np

In [294]:
M = ri(1,100,25).reshape(5,5)

In [295]:
M

array([[30, 14, 80, 93, 81],
       [84, 99, 84, 71, 92],
       [91, 12, 82, 25, 99],
       [77,  6, 26, 51, 94],
       [12, 89, 52, 92, 36]])

In [297]:
np.sort(M,axis=0)

array([[12,  6, 26, 25, 36],
       [30, 12, 52, 51, 81],
       [77, 14, 80, 71, 92],
       [84, 89, 82, 92, 94],
       [91, 99, 84, 93, 99]])

In [59]:
np.sort(M)

array([[ 4, 12, 22, 71, 92],
       [ 3,  9, 19, 24, 44],
       [12, 13, 22, 31, 34],
       [17, 20, 57, 73, 88],
       [27, 31, 41, 86, 95]])

In [61]:
np.sort(M, axis=0)

array([[ 9,  4,  3, 12, 13],
       [20, 17, 12, 27, 22],
       [22, 19, 34, 44, 24],
       [41, 31, 86, 57, 31],
       [92, 95, 88, 71, 73]])

In [314]:
a = ri(1,100,30)
b = a.reshape(6,5)
b

array([[34, 90,  8, 71, 38],
       [75, 64, 36, 30, 16],
       [16, 30, 89, 41, 36],
       [59, 73,  8, 69, 49],
       [11, 78, 24, 64, 37],
       [97, 90, 68, 90, 46]])

In [315]:
a

array([34, 90,  8, 71, 38, 75, 64, 36, 30, 16, 16, 30, 89, 41, 36, 59, 73,
        8, 69, 49, 11, 78, 24, 64, 37, 97, 90, 68, 90, 46])

In [316]:
a.max()

97

In [317]:
a.min()

8

In [318]:
b

array([[34, 90,  8, 71, 38],
       [75, 64, 36, 30, 16],
       [16, 30, 89, 41, 36],
       [59, 73,  8, 69, 49],
       [11, 78, 24, 64, 37],
       [97, 90, 68, 90, 46]])

In [319]:
b.max(axis=0)

array([97, 90, 89, 90, 49])

In [320]:
b.min()

8

In [321]:
b

array([[34, 90,  8, 71, 38],
       [75, 64, 36, 30, 16],
       [16, 30, 89, 41, 36],
       [59, 73,  8, 69, 49],
       [11, 78, 24, 64, 37],
       [97, 90, 68, 90, 46]])

In [322]:
b.max(axis=1)

array([90, 75, 89, 73, 78, 97])

In [323]:
b.max(axis=0)

array([97, 90, 89, 90, 49])

In [324]:
b

array([[34, 90,  8, 71, 38],
       [75, 64, 36, 30, 16],
       [16, 30, 89, 41, 36],
       [59, 73,  8, 69, 49],
       [11, 78, 24, 64, 37],
       [97, 90, 68, 90, 46]])

In [325]:
l=[1,2,3,4]
a="string"

In [326]:
a.find("z")

-1

In [327]:
b

array([[34, 90,  8, 71, 38],
       [75, 64, 36, 30, 16],
       [16, 30, 89, 41, 36],
       [59, 73,  8, 69, 49],
       [11, 78, 24, 64, 37],
       [97, 90, 68, 90, 46]])

In [330]:
b.argmax(axis=0 )

array([5, 0, 2, 5, 3], dtype=int64)

In [31]:
b.argmax(axis=0)

array([0, 2, 5, 3, 3], dtype=int64)

# Indexing and slicing

In [331]:
l=[1,3,6,12,45,67,98,65,23]

In [333]:
l[2,3,5,6,8]

TypeError: list indices must be integers or slices, not tuple

In [334]:
arr = np.arange(10,20)

In [335]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [337]:
arr[[2,3,5,7,8]]

array([12, 13, 15, 17, 18])

In [38]:
arr[-1:-5:-1]

array([10,  9,  8,  7])

In [338]:
arr[-1]

19

In [339]:
arr[3:6]

array([13, 14, 15])

In [340]:
arr[:4]

array([10, 11, 12, 13])

In [341]:
arr = np.arange(0,21,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [342]:
l=[1,2,3,4,5,6]

In [343]:
l[0:3]

[1, 2, 3]

In [344]:
arr[[2,4,9]]

array([ 4,  8, 18])

In [345]:
mat = np.array(ri(10,100,15)).reshape(3,5)
mat

array([[23, 57, 43, 75, 74],
       [64, 55, 28, 55, 67],
       [52, 27, 67, 79, 58]])

In [349]:
mat[1:3,1:4]

array([[55, 28, 55],
       [27, 67, 79]])

In [353]:
mat[(mat>50) & (mat%2!=0)]

array([57, 75, 55, 55, 67, 67, 79])

In [69]:
mat[mat%2==0]

array([66, 14, 38, 38, 54, 22])

In [50]:
mat[2,4]

11

In [54]:
mat[0]

array([14, 86, 88, 86, 43])

In [56]:
mat[0:3,0:2]

array([[14, 86],
       [55, 88],
       [39, 91]])

Matrix with row indices 0 and 1 and column indices 1 and 3

In [59]:
mat[:,]

array([[14, 86, 88, 86, 43],
       [55, 88, 43, 65, 89],
       [39, 91, 38, 51, 74]])

### boolean Subseting

In [51]:
mat = np.array(ri(10,100,15)).reshape(3,5)

In [55]:
mat

array([[49, 66, 14, 23, 38],
       [75, 43, 38, 25, 49],
       [87, 54, 22, 95, 17]])

In [60]:
mat[(mat>35) | (mat%2!=0)]

array([49, 66, 23, 38, 75, 43, 38, 25, 49, 87, 54, 95, 17])

In [234]:
mat[mat!=50]

array([95, 93, 67, 94, 24, 38, 21, 91, 30, 37, 22, 46, 22, 10, 91])

# Universal Functions

In [354]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)

In [355]:
mat1

array([[1, 3, 5],
       [3, 4, 7],
       [6, 5, 4]])

In [356]:
mat2

array([[9, 3, 5],
       [2, 1, 1],
       [9, 2, 5]])

In [357]:
mat1+mat2

array([[10,  6, 10],
       [ 5,  5,  8],
       [15,  7,  9]])

In [358]:
mat1*mat2

array([[ 9,  9, 25],
       [ 6,  4,  7],
       [54, 10, 20]])

In [359]:
mat1/mat2

array([[0.11111111, 1.        , 1.        ],
       [1.5       , 4.        , 7.        ],
       [0.66666667, 2.5       , 0.8       ]])

In [360]:
3*mat1-2*mat2

array([[-15,   3,   5],
       [  5,  10,  19],
       [  0,  11,   2]])

In [362]:
mat1

array([[1, 3, 5],
       [3, 4, 7],
       [6, 5, 4]])

In [363]:
100+mat1

array([[101, 103, 105],
       [103, 104, 107],
       [106, 105, 104]])

In [364]:
mat1**.5

array([[1.        , 1.73205081, 2.23606798],
       [1.73205081, 2.        , 2.64575131],
       [2.44948974, 2.23606798, 2.        ]])

In [81]:
pow(mat1,0.5)

array([[1.41421356, 1.        , 1.        ],
       [2.23606798, 1.73205081, 1.        ],
       [1.73205081, 3.        , 2.        ]])

# Broadcasting

In [365]:
start = np.zeros((4,4))

In [366]:
start

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [381]:
add_rows = np.array([1, 0, 2,3]).reshape(4,1)

In [382]:
start

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [383]:
start+add_rows

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [384]:
start

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [385]:
np.hstack((start,add_rows))

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 2.],
       [0., 0., 0., 0., 3.]])

In [379]:
add_rows

array([[1, 0, 2, 3]])

In [100]:
np.hstack((start,col))

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 2.],
       [0., 0., 0., 0., 3.]])

In [386]:
add_cols = np.array([[0,1,2,3]])
add_cols

array([[0, 1, 2, 3]])

In [387]:
add_cols = add_cols.T

In [388]:
add_cols

array([[0],
       [1],
       [2],
       [3]])

In [389]:
np.hstack((start,add_cols))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 2.],
       [0., 0., 0., 0., 3.]])

In [116]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [117]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
b=np.array([10,20,30],ndmin=3)

In [126]:
b

array([[[10, 20, 30]]])

In [119]:
c=b.T

In [120]:
c

array([[10],
       [20],
       [30]])

In [121]:
np.hstack((a,c))

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30]])

In [122]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30]])

In [101]:
a=add_rows.T
a

array([1, 0, 2])

In [97]:
start

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [105]:
a=np.array(a,ndmin=2)

In [110]:
a=a.T

In [ ]:
polymorphism

over riding
over loading

In [132]:
class employee():
    def department(self):
        return("my dept is operations")

In [134]:
employee.mro()

[__main__.employee, object]

In [141]:
class employee():
    def dept(self):
        print("my dept is operations")
    def dept(self,dept):
        print("my dept is {}".format(dept))

In [142]:
esh=employee()

In [146]:
esh.dept()

TypeError: dept() missing 1 required positional argument: 'dept'

In [111]:
np.hstack((start,a))

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 2.]])